package src.Parser;
/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LET = 5;
  /** RegularExpression Id. */
  int IN = 6;
  /** RegularExpression Id. */
  int TRUE = 7;
  /** RegularExpression Id. */
  int FALSE = 8;
  /** RegularExpression Id. */
  int PLUS = 9;
  /** RegularExpression Id. */
  int MINUS = 10;
  /** RegularExpression Id. */
  int STAR = 11;
  /** RegularExpression Id. */
  int DIV = 12;
  /** RegularExpression Id. */
  int LPAR = 13;
  /** RegularExpression Id. */
  int RPAR = 14;
  /** RegularExpression Id. */
  int LBRA = 15;
  /** RegularExpression Id. */
  int RBRA = 16;
  /** RegularExpression Id. */
  int EQUAL = 17;
  /** RegularExpression Id. */
  int COLON = 18;
  /** RegularExpression Id. */
  int SEMIC = 19;
  /** RegularExpression Id. */
  int TERM = 20;
  /** RegularExpression Id. */
  int COMMA = 21;
  /** RegularExpression Id. */
  int AND = 22;
  /** RegularExpression Id. */
  int OR = 23;
  /** RegularExpression Id. */
  int EQ = 24;
  /** RegularExpression Id. */
  int GT = 25;
  /** RegularExpression Id. */
  int LT = 26;
  /** RegularExpression Id. */
  int GTEQ = 27;
  /** RegularExpression Id. */
  int LTEQ = 28;
  /** RegularExpression Id. */
  int DIF = 29;
  /** RegularExpression Id. */
  int NOT = 30;
  /** RegularExpression Id. */
  int ASSIGN = 31;
  /** RegularExpression Id. */
  int BOX = 32;
  /** RegularExpression Id. */
  int MATCH = 33;
  /** RegularExpression Id. */
  int IF = 34;
  /** RegularExpression Id. */
  int THEN = 35;
  /** RegularExpression Id. */
  int ELSE = 36;
  /** RegularExpression Id. */
  int WHILE = 37;
  /** RegularExpression Id. */
  int DO = 38;
  /** RegularExpression Id. */
  int END = 39;
  /** RegularExpression Id. */
  int PRINT = 40;
  /** RegularExpression Id. */
  int PRINTLN = 41;
  /** RegularExpression Id. */
  int FN = 42;
  /** RegularExpression Id. */
  int ARROW = 43;
  /** RegularExpression Id. */
  int APP = 44;
  /** RegularExpression Id. */
  int String = 45;
  /** RegularExpression Id. */
  int Id = 46;
  /** RegularExpression Id. */
  int Num = 47;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"let\"",
    "\"in\"",
    "\"true\"",
    "\"false\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\":\"",
    "\";\"",
    "\";;\"",
    "\",\"",
    "\"&&\"",
    "\"||\"",
    "\"==\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"~=\"",
    "\"~\"",
    "\":=\"",
    "\"box\"",
    "\"match\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"while\"",
    "\"do\"",
    "\"end\"",
    "\"print\"",
    "\"println\"",
    "\"fn\"",
    "\"=>\"",
    "\"app\"",
    "<String>",
    "<Id>",
    "<Num>",
  };

}
